Repository NMAI-lab/SAVI, pull requests merged in 2019-05, with the labels that each got.

#151 Behaviour debug
  saviSimulation/savi/agentBehaviour/SimpleJasonAgent.java
  saviSimulation/savi/asl/uav.asl
  saviSimulation/savi/asl/ugv.asl
  saviSimulation/savi/jason_processing/Geometry.java
  saviSimulation/savi/jason_processing/UxV.java
Labels: behaviour, bug

#158 Update README.md
  README.md
Labels: wiki

#156 Sockets connection to Command station
  saviSimulation/savi/commandStation/CommandStationCore.java
  saviSimulation/savi/commandStation/CommandStationGUI.java
  saviSimulation/savi/commandStation/CommandStationSocketConnector.java
  saviSimulation/savi/commandStation/MessageHandler.java
  saviSimulation/savi/commandStation/SocketConnector.java
  saviSimulation/savi/commandStation/TelemetryFetcher.java
  saviSimulation/savi/jason_processing/FieldAntenna.java
Labels: enhancement

#165 Console cleanup
  saviSimulation/savi/StateSynchronization/SyncAgentState.java
  saviSimulation/savi/UxVInternalActions/GetAbsolutePosition.java
  saviSimulation/savi/UxVInternalActions/GetRelativePosition.java
  saviSimulation/savi/agentBehaviour/SimpleJasonAgent.java
  saviSimulation/savi/commandStation/SocketConnector.java
  saviSimulation/savi/jason_processing/AgentModel.java
  saviSimulation/savi/jason_processing/SAVIWorld_model.java
  saviSimulation/savi/jason_processing/SAVI_Controller.java
  saviSimulation/savi/jason_processing/Threat.java
  saviSimulation/savi/jason_processing/UaVBehavior.java
  saviSimulation/savi/jason_processing/UgVBehavior.java
  saviSimulation/savi/jason_processing/UxVBehavior.java
  saviSimulation/savi/jason_processing/WorldObject.java
  saviSimulation/testLogging.properties
Labels: bug, enhancement
